//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoomCloser.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoomCloser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get the number of participants due to a bug. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Zoom shortcut is different from the expected (standard), please change it to continue using it: Manage Participants (ALT+T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DifferentShortcuts {
            get {
                return ResourceManager.GetString("DifferentShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left the meeting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitMeeting {
            get {
                return ResourceManager.GetString("ExitMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom is minimized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minimized {
            get {
                return ResourceManager.GetString("Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit when the number of participants drops below {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NormalExitCondition {
            get {
                return ResourceManager.GetString("NormalExitCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenMovieFolder {
            get {
                return ResourceManager.GetString("OpenMovieFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the participants window. You may close it immediately. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenParticipantsWindow {
            get {
                return ResourceManager.GetString("OpenParticipantsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Participants Current:{0}, Max:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParticipantCount {
            get {
                return ResourceManager.GetString("ParticipantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Participated in a meeting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParticipatedInMeeting {
            get {
                return ResourceManager.GetString("ParticipatedInMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started capturing the number of participants に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartedCapturingTHeNumberOfParticipants {
            get {
                return ResourceManager.GetString("StartedCapturingTHeNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software forced to exit a meeting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThisSoftwareForcedToExitMeeting {
            get {
                return ResourceManager.GetString("ThisSoftwareForcedToExitMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The software will not automatically exit until the maximum number of participants exceeds {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnderOrEqualsToThresholdExitCondition {
            get {
                return ResourceManager.GetString("UnderOrEqualsToThresholdExitCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User forced to exit a meeting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserForcedToExitMeeting {
            get {
                return ResourceManager.GetString("UserForcedToExitMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom is not running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZoomNotRunning {
            get {
                return ResourceManager.GetString("ZoomNotRunning", resourceCulture);
            }
        }
    }
}
