# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "ZoomCloser.sln"
[github]
user = "34j"
repo = "ZoomCloser"
[[pack]]
rid = ["win-x64"]
kinds = ["zip", "tar"]
[nuget]
publish = false