name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Translate
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Copying README.ja.md to README.md
        run: |
          cp -f README.ja.md README.md
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      - name: Copying README.en.md to README.md
        run: |
          cp -f README.en.md README.md
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Renamed README.en.md to README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
