name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Translate
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Copying README.ja.md to README.md
        run: |
          cp -f README.ja.md README.md
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      - name: Copying README.en.md to README.md
        run: |
          cp -f README.en.md README.md
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
		with: 
		  commit_message: Added Readme.md
